# Generated by Django 5.1.6 on 2025-02-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('personal', '개인 즐겨 찾기'), ('work', '업무 활용 자료'), ('refer', '참고 자료'), ('edu', '교육 및 학습 자료'), ('others', '기타 자료')], default='personal', max_length=20)),
            ],
        ),
    ]
