# Generated by Django 5.1.6 on 2025-02-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblink',
            name='created_by',
            field=models.CharField(max_length=20),
        ),
    ]
