# Generated by Django 5.1.6 on 2025-02-17 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_role'),
        ('feeds', '0002_alter_weblink_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblink',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_links', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='weblink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
