# Generated by Django 5.1.6 on 2025-02-18 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_role'),
        ('feeds', '0003_weblink_editors_alter_weblink_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblink',
            name='editors',
        ),
        migrations.AlterField(
            model_name='weblink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', to_field='username'),
        ),
    ]
