# Generated by Django 5.1.6 on 2025-02-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_role'),
        ('feeds', '0004_remove_weblink_editors_alter_weblink_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblink',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_links', to='accounts.account'),
        ),
    ]
