# Generated by Django 5.1.6 on 2025-02-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_createdat_account_updatedat_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('user', '일반 사용자'), ('admin', '관리자')], default='user', max_length=20),
        ),
    ]
